# Configuration for plugin behavior

# Config file version. Do not change this
configVersion: 1

# Config options for the /itemlore command
itemLore:
#   Blacklist for items
#   Item ids placed here will Cannot be Modified by anyone
  protectedMaterials:
#    - minecraft:experience_bottle