name: EditItemData
version: '${project.version}'
main: net.wycre.itemlore.Main
api-version: 1.18
authors: [ Aclamendo ]
description: Allows users to modify an item's NBT data using a command
website: www.wycre.net
tab-complete: 0
commands:
  itemlore:
    description: Modifies the lore of an item (supports color codes)
    usage: /<command> <add/remove> [text]
  itemname:
    description: Sets the name of an item (supports color codes)
    usage: /<command> [text]
